ABF:
  farms:
    cactusexample:
      sizes:
        small:
          fancyname: §bSmall
          schematic: cactusExampleSmall.schematic
          price: 10
          materials:
            '0':
              ==: org.bukkit.inventory.ItemStack
              type: CACTUS
        medium:
          fancyname: §6Medium'
          schematic: cactusExampleMedium.schematic
          price: 100
          materials:
            '0':
              ==: org.bukkit.inventory.ItemStack
              type: CACTUS
              amount: 10
  general:
    itemheader: '&6&k|&r&6AutoFarm&k|&r'
    farmblock:
      ==: org.bukkit.inventory.ItemStack
      type: CHEST
    schematicdirectory: schematics
